### ISSUE TITLE
intersystems@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by InfoAlenia** [intersystems/quickstarts-nodejs#1]
run npm install --save intersystems iris native causes:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/intersystems - Not found
npm ERR! 404 
npm ERR! 404  'intersystems@latest' is not in the npm registry.
**npm ERR! 404 **You should bug the author to publish it (or use the name yourself!)****

error while

**Comment by isc-rsingh** [comment]
@InfoAlenia did you do the prior step?
`cd Solutions`

That's the error I get if I skip that step.

**Comment by isc-acoppola** [comment]
Added instructions for getting intersystems-iris-native driver from install directory.

**Comment by isc-acoppola** [comment]
Added instructions for getting intersystems-iris-native driver from install directory.
